In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
dataset = pd.read_csv('/content/Data.csv')
x = dataset.iloc[:, :3].values
y = dataset.iloc[:, -1].values

In [15]:
# Cek apakah ada missing value dengan fungsi isnull()
mv = dataset.isnull().sum() # sum() fungsi untuk menghitung total dari missing value
print(mv)

Country      0
Age          1
Salary       2
Purchased    0
dtype: int64


In [16]:
print(x)

[['Malaysia' 44.0 72000.0]
 ['Singapore' 27.0 48000.0]
 ['Thailand' 30.0 nan]
 ['Indonesia' nan 61000.0]
 ['Indonesia' 40.0 25000.0]
 ['Singapore' 35.0 58000.0]
 ['Thailand' 40.0 52000.0]
 ['Malaysia' 48.0 nan]
 ['Indonesia' 50.0 83000.0]
 ['China' 30.0 67000.0]]


In [17]:
print(y)

['No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes']


In [18]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
# Cara lain mengisi data pada data yang bernilai missing value
# age_median = x['Age'].median() #untuk mengetahui nilai media kolom Age
# salary_median = x['Salary'].median() #untuk mengetahui nilai media kolom Salary

# x['Age'].fillna(age_median, inplace=True)
# x['Salary'].fillna(salary_median, inplace=True)

In [19]:
print(x)

[['Malaysia' 44.0 72000.0]
 ['Singapore' 27.0 48000.0]
 ['Thailand' 30.0 58250.0]
 ['Indonesia' 38.22222222222222 61000.0]
 ['Indonesia' 40.0 25000.0]
 ['Singapore' 35.0 58000.0]
 ['Thailand' 40.0 52000.0]
 ['Malaysia' 48.0 58250.0]
 ['Indonesia' 50.0 83000.0]
 ['China' 30.0 67000.0]]


In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [21]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 1.0 30.0 58250.0]
 [0.0 1.0 0.0 0.0 0.0 38.22222222222222 61000.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 25000.0]
 [0.0 0.0 0.0 1.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 1.0 40.0 52000.0]
 [0.0 0.0 1.0 0.0 0.0 48.0 58250.0]
 [0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 30.0 67000.0]]


In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [23]:
print(y)

[0 1 0 1 0 1 1 1 0 1]


In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [25]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 40.0 52000.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 25000.0]
 [0.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 38.22222222222222 61000.0]
 [0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 0.0 48.0 58250.0]
 [0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 0.0 35.0 58000.0]]


In [26]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 30.0 58250.0]
 [1.0 0.0 0.0 0.0 0.0 30.0 67000.0]]


In [27]:
print(y_train)

[1 0 0 1 1 1 0 1]


In [28]:
print(y_test)

[0 1]


In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [30]:
print(x_train)

[[0.0 0.0 0.0 -0.5773502691896258 2.6457513110645903 -0.04048881650894592
  -0.3221581110696072]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272
  -0.04048881650894592 -2.0090951290340957]
 [0.0 0.0 1.0 -0.5773502691896258 -0.3779644730092272 0.5425501412198735
  0.9274248652003844]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272
  -0.29961724216619917 0.24015422825188898]
 [0.0 0.0 0.0 1.7320508075688774 -0.3779644730092272 -1.9353654291276094
  -0.5720747063236055]
 [0.0 0.0 1.0 -0.5773502691896258 -0.3779644730092272 1.1255890989486932
  0.06833656901476516]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 1.417108577813103
  1.6146955021488796]
 [0.0 0.0 0.0 1.7320508075688774 -0.3779644730092272 -0.7692875136699703
  0.052716781811390265]]


In [31]:
print(x_test)

[[0.0 0.0 0.0 -0.5773502691896258 2.6457513110645903 -1.4980862108309947
  0.06833656901476516]
 [1.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 -1.4980862108309947
  0.6150291211328864]]
